/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDataAssetItemDialog: typeof import('./src/components/common/AddDataAssetItemDialog.vue')['default']
    AddProjectDialog: typeof import('./src/components/common/AddProjectDialog.vue')['default']
    AssetsStoreDialog: typeof import('./src/components/common/AssetsStoreDialog.vue')['default']
    DataAssetListItem: typeof import('./src/components/common/DataAssetListItem.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/common/Header.vue')['default']
    ProcessingProjectDialog: typeof import('./src/components/common/ProcessingProjectDialog.vue')['default']
    ProjectCard: typeof import('./src/components/common/ProjectCard.vue')['default']
    ProjectStatusCard: typeof import('./src/components/common/ProjectStatusCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoDataAssetDialog: typeof import('./src/components/common/VideoDataAssetDialog.vue')['default']
  }
}
